baseurl = "https://ikergalardi.github.io"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Iker Galardi"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  #subtitle = ""
  mainSections = ["post","posts"]
  logo = "img/avatar.jpeg" # Expecting square dimensions
  favicon = "img/avatar.jpeg"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "Iker Galardi"
  website = "ikergalardi.github.io"
  github = "IkerGalardi"
  linkedin = "IkerGalardi"
  youtube = "user/username" # or channel/channelname

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4

[[menu.main]]
    name = "Projects"
    url = "page/projects/"
    weight = 3
